**Question:** Create a Dense layer with 5 neurons and apply this on tensor of (6,6) with a multiplier 1.5,apply a kernel regularizer L2 and initializer GlorotUniform and print the output.

**Description:** 
* Import the required libraries.
* Create a tensor and a dense layer 
* Create a regularizer variable and initializer variable
* Create a tensor with multiplier 
* Apply the layer on tensor and print the output.


**Sample Output format :**

Tensor

**Sample Output:**

tf.Tensor(

[[ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]

 [ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]

 [ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]

 [ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]

 [ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]

 [ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]], shape=(6, 5), dtype=float32)

* Hint 01: use tensorflow library
* Hint 02: create a dense layer using tf.keras.layers.Dense()
* Hint 03: for regularizer tf.keras.regularizers,for initializers tf.keras.initializers

In [ ]:
#start your code here

In [6]:
#import library
import tensorflow as tf

In [7]:
#create a tensor
tensor = tf.ones(shape=(6,6))*1.5

In [8]:
initializer=tf.keras.initializers.GlorotUniform()
regularizer=tf.keras.regularizers.L2()

In [9]:
#create a dense layer and pass the tensor through it
layer=tf.keras.layers.Dense(5,input_dim=5,kernel_initializer=initializer,kernel_regularizer=regularizer)
output=layer(tensor)

In [10]:
#print the output
print(output)


tf.Tensor(
[[ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]
 [ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]
 [ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]
 [ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]
 [ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]
 [ 3.7209575  -1.302359   -1.086782    3.148315    0.68989354]], shape=(6, 5), dtype=float32)
