**Question:**  Create a dense layer with ‘5’ neurons and apply a L1 L2  regularization penalty of ‘0.5’,‘0.25’ ,pass a tensor of shape(3,6) with a multiplier ‘1.5’ and print the result



**Description:** 
* Import the required libraries.
* Ask for the sample input for creating a tensor of ones,multiplier and also ask for input for the value of  L1L2 penalty.
* Create a Dense layer.
* Create a tensor with multiplier 
* Apply the layer on tensor and print the output.


**Sample Output format :**

Tensor

**Sample Output:**

tf.Tensor(

[[9. 9. 9. 9. 9.]

 [9. 9. 9. 9. 9.]

 [9. 9. 9. 9. 9.]], shape=(3, 5), dtype=float32)

* Hint 01: use tensorflow library
* Hint 02: create dense layer using tf.keras.layers.Dense()
* Hint 03: use regularizers using tf.keras.regularizers.L1L2


In [ ]:
#start your code here

In [9]:
#import library
import tensorflow as tf

In [10]:
#create a tensor
tensor = tf.ones(shape=(3, 6)) * 1.5

In [11]:
#create a dense layer and pass the tensor through it
layer = tf.keras.layers.Dense(5, input_dim=5,kernel_initializer='ones',kernel_regularizer=tf.keras.regularizers.L1L2(0.5,0.25))
out = layer(tensor)


In [12]:
#print the output
print(out)

tf.Tensor(
[[9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]], shape=(3, 5), dtype=float32)
