**Question**:  Read a image with the help of tensorflow and convert to array and print the array.


**Description:**
* Enter the single input string,  path of image 
* Reed the image  with the help of keras and tensorflow .
* Apply preprocessing.image, use load_img() function
* Use image_to_array() function
* Print the result i.e., size of the  input sample


**Input format:**  String


**Output format:**  nd array





**Sample input:**




**Sample output:**

[[[ 92. 192. 164.]

  [ 91. 191. 163.]
  
  [ 89. 189. 161.]
  
  ...
  
  [110. 200. 174.]
  
  [110. 200. 174.]
  
  
  [110. 200. 174.]]

 [[ 92. 192. 164.]
 
  [ 91. 191. 163.]
  
  [ 89. 189. 161.]
  
  ...
  
  [111. 201. 175.]
  
  [111. 201. 175.]
  
  [112. 202. 176.]]

 [[ 92. 192. 164.]
 
  [ 90. 190. 162.]
  
  [ 89. 189. 161.]
  
  ...
  
  [112. 202. 176.]
  
  [112. 202. 176.]
  
  [112. 202. 176.]]

 ...

 [[151. 215. 191.]
 
  [151. 215. 191.]
  
  [151. 215. 191.]
  ...
  
  [159. 220. 202.]
  
  [161. 218. 199.]
  
  [161. 218. 199.]]


 [[151. 215. 191.]
 
  [151. 215. 191.]
  
  [151. 215. 191.]
  
  ...
  
  [159. 220. 202.]
  
  [161. 218. 199.]
  
  [161. 218. 199.]]


 [[151. 215. 191.]
 
  [151. 215. 191.]
  
  [151. 215. 191.]
  
  ...
  
  [158. 219. 201.]
  
  [161. 218. 199.]
  
  [161. 218. 199.]]]







**Hint1:** Use tensorflow,keras,preprocessing.image

**Hint2:** Use load_img() function

**Hint3:** Use img_to_array()  function
 



In [1]:
# Start Your Code Here.

In [1]:
# import libraries
import tensorflow as tf
import os
path='banana_1.jpg'
image = tf.keras.preprocessing.image.load_img(path)
image=tf.keras.preprocessing.image.img_to_array(image)
print(image)
 


[[[ 92. 192. 164.]
  [ 91. 191. 163.]
  [ 89. 189. 161.]
  ...
  [110. 200. 174.]
  [110. 200. 174.]
  [110. 200. 174.]]

 [[ 92. 192. 164.]
  [ 91. 191. 163.]
  [ 89. 189. 161.]
  ...
  [111. 201. 175.]
  [111. 201. 175.]
  [112. 202. 176.]]

 [[ 92. 192. 164.]
  [ 90. 190. 162.]
  [ 89. 189. 161.]
  ...
  [112. 202. 176.]
  [112. 202. 176.]
  [112. 202. 176.]]

 ...

 [[151. 215. 191.]
  [151. 215. 191.]
  [151. 215. 191.]
  ...
  [159. 220. 202.]
  [161. 218. 199.]
  [161. 218. 199.]]

 [[151. 215. 191.]
  [151. 215. 191.]
  [151. 215. 191.]
  ...
  [159. 220. 202.]
  [161. 218. 199.]
  [161. 218. 199.]]

 [[151. 215. 191.]
  [151. 215. 191.]
  [151. 215. 191.]
  ...
  [158. 219. 201.]
  [161. 218. 199.]
  [161. 218. 199.]]]
