**Question**: Load, split, and preprocess the sarcasm dataset using tokenizer by including vocabulary size as 1000, post padding, and maximum sentence length as 120


**Level**: Easy

**Input format:** json format


**Output format:** array


**Sample input:** Sarcasm dataset


**Sample output**:

[[  1   1   1 ...   0   0   0]

[202   1   8 ...   0   0   0]

[ 18 380 191 ...   0   0   0]

...

[  1   9  67 ...   0   0   0]

[  1 374   1 ...   0   0   0]

[  1   1   6 ...   0   0   0]]


**Solution**:

In [ ]:
import json
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

with open("/home/metagogy/Downloads/sarcasm.json", 'r') as d:
    data = json.load(d)
    
sentences = []
labels = []
urls = []
for i in data:
    sentences.append(i['headline'])
    labels.append(i['is_sarcastic'])

training_sentences = sentences[0:20000]
testing_sentences = sentences[20000:]
training_labels = labels[0:20000]
testing_labels = labels[20000:]

tokenizer = Tokenizer(num_words=1000, oov_token="<OOV>")
tokenizer.fit_on_texts(training_sentences)

word_index = tokenizer.word_index

training_sequences = tokenizer.texts_to_sequences(training_sentences)
training_padded = pad_sequences(training_sequences, maxlen=120, padding='post', truncating='post')

testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequences, maxlen=120, padding='post', truncating='post')