**Question:** Read a sentence as input, apply the CountVectorizer function find a bag of words, and print the result to the console.

**Note :** Use nltk library.

from sklearn.feature_extraction.text import CountVectorizer 

**Topic Name:** Bag of Words


**Input format:** Read a sentence from the standard input.


**Output format:** List that vector format contain words

**Sample Input:**
the sun is shining,the weather is good,the sun is shining and the weather is good


**Sample Output:**



[[0 0 1 1 1 1 0]
 
 [0 1 1 0 0 1 1]
 
 [1 1 2 1 1 2 1]]

In [4]:
import numpy as np
import nltk
from nltk import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer 

In [5]:
a=input().split(",")

the sun is shining,the weather is good,the sun is shining and the weather is good


In [6]:
cv = CountVectorizer()

In [7]:
df= cv.fit_transform(a).toarray() 
print(df)

[[0 0 1 1 1 1 0]
 [0 1 1 0 0 1 1]
 [1 1 2 1 1 2 1]]
