**Question**:  Read an image with the help of tensorflow and convert to array and apply Conv2D layers BatchNormalization,Conv2D,BatchNormalization on it and  print the array shape.




**Description:**
* Enter the single input string,  path of image 
* Reed the image  with the help of keras and tensorflow .
* Apply preprocessing.image, use load_img() function
* Use image_to_array(), reshape function
* Create Sequential model and apply Conv2D with filter as 3x3 and padding as same
* Use MaxPooling2D
* Predict the model and print the array 




**Input format:**  String


**Output format:**  ndarray




**Sample input:**



**Sample output:**

[[ 91.0951    85.64975   12.114864 ...  98.91874   90.012566  13.513168]

 [ 91.0951    85.64975   12.114864 ... 100.17621   90.97379   13.706427]

 [ 91.0951    85.64975   12.114864 ... 100.17621   90.97379   13.706427]

 ...

 [114.940254  97.989075  16.514252 ... 119.53957  100.44514   17.325138]

 [114.940254  97.989075  16.514252 ... 119.53957  100.44514   17.325138]
 
 [114.940254  97.989075  16.514252 ... 119.53957  100.44514   17.325138]]
 

**Hint1:** Use tensorflow,keras,preprocessing.image

**Hint2:** Use load_img(), img_to_array() function

**Hint3:** Use reshape, Conv2D  function



In [ ]:
# Start Your Code Here.

In [1]:
# import libraries
import tensorflow as tf
import keras
from keras import Sequential
from keras.layers import Dense, Activation,Flatten
from keras.layers import Conv2D, BatchNormalization




In [4]:
path='banana_1.jpg'
image = tf.keras.preprocessing.image.load_img(path)
image=tf.keras.preprocessing.image.img_to_array(image)
lst=list(image.shape)
image=image.reshape((lst[0],lst[1],lst[2],1))
img=image.reshape(lst[0]*lst[1],lst[2],1)


In [5]:
model = Sequential()
model.add(Conv2D(1, (3, 3),padding='same',input_shape=image.shape))
model.add(BatchNormalization())
model.add(Conv2D(1, (3, 3),padding='same'))
model.add(BatchNormalization())
model.add(Flatten())
x=model.predict(image)
print(x)


[[ 91.0951    85.64975   12.114864 ...  98.91874   90.012566  13.513168]
 [ 91.0951    85.64975   12.114864 ... 100.17621   90.97379   13.706427]
 [ 91.0951    85.64975   12.114864 ... 100.17621   90.97379   13.706427]
 ...
 [114.940254  97.989075  16.514252 ... 119.53957  100.44514   17.325138]
 [114.940254  97.989075  16.514252 ... 119.53957  100.44514   17.325138]
 [114.940254  97.989075  16.514252 ... 119.53957  100.44514   17.325138]]
