**Question :** Create a numpy array of range 16 and reshape it to (4,4) and print the output

**Explanation:**
* Create an array  and reshape it.
* Print the result.


**Sample Output:**

Numpy array

**Sample Output:**

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

* Hint 01:  create a array using numpy.arange()

* Hint 02: for reshape numpy.reshape()



In [1]:
#start your code here

In [1]:
#import library
import numpy

In [2]:
#create a numpy array and reshape it
data = numpy.arange(16).reshape(4, 4)

In [3]:
#print the output
print(data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
