**Question :** Create an MxN dimensional array. Perform element-wise mathematical operations such as a sign, ceil, round, and np.rint on created array and print all outputs line by line.

**Level :** Hard

**Input format :**

Integer     # M rows

Integer     # N columns

M rows N columns.

**Output format :** Arrays.

**Sample input :**

**Sample output :**

In [2]:
import numpy as np
m=int(input())
n=int(input())
arr = np.array([list(map(float,input().split())) for i in range(m)])

3
3
10 20 30
-10 -20 -30
10.25 20.25 30.25


In [4]:
print(np.sign(arr))

[[ 1.  1.  1.]
 [-1. -1. -1.]
 [ 1.  1.  1.]]


In [5]:
print(np.ceil(arr))

[[ 10.  20.  30.]
 [-10. -20. -30.]
 [ 11.  21.  31.]]


In [6]:
print(np.round(arr))

[[ 10.  20.  30.]
 [-10. -20. -30.]
 [ 10.  20.  30.]]


In [7]:
print(np.rint(arr))

[[ 10.  20.  30.]
 [-10. -20. -30.]
 [ 10.  20.  30.]]
