**Question:** Create a Dense layer with ‘n’ neurons, apply kernel initializer of GlorotUniform and also apply a regularizer of ‘l2’and create a tensor with a multiplier of ‘m’ and pass it through the layer and print the output.



**Level :02**

**Sample Input format:**

Number

Number

Number


**Sample Output format :**

Tensor





**Sample Input:**

6<br/>
2<br/>
0.2



**Sample Output:**

tf.Tensor(<br/>[[ 1.8108822  1.7334914  2.0615597  1.0337727 -3.6930838  1.6053721]<br/> 
 [ 1.8108822  1.7334914  2.0615597  1.0337727 -3.6930838  1.6053721]<br/> 
 [ 1.8108822  1.7334914  2.0615597  1.0337727 -3.6930838  1.6053721]<br/> 
 [ 1.8108822  1.7334914  2.0615597  1.0337727 -3.6930838  1.6053721]<br/>
 [ 1.8108822  1.7334914  2.0615597  1.0337727 -3.6930838  1.6053721]<br/> 
 [ 1.8108822  1.7334914  2.0615597  1.0337727 -3.6930838  1.6053721]],shape=(6, 6), dtype=float32)

In [ ]:
#start your code here

In [ ]:
#import your library
#complete your code here

In [ ]:
#take the respective inputs
n=(#complete your code here)
m=(#complete your code here)
l2=(#complete your code here)

In [ ]:
#Apply the initializer in to a variable
initializer=#complete your code here

In [ ]:
#apply the dense layer with the initializer and regularizer.
layer = #complete your code here

In [ ]:
#create the tensor and apply the layer on it.
tensor =#complete your code here
out = #complete your code here

In [ ]:
#print the output
print(out)