**Question:** Create a dense layer with ‘n’ neurons and apply a L1_L2 regularization penalty of 'l1',‘l2’ ,pass a tensor of shape(n,n) with a multiplier ‘m’ and print the result.

**Level :02**

**Sample Input format:**
* Number
* Number
* Number
* Number

**Sample Output format :**
* Tensor


**Sample Input:**

6<br/>
2<br/>
0.2<br/>
0.15

**Sample Output:**

tf.Tensor(<br/>[[12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]],shape=(6, 6), dtype=float32)

In [ ]:
#start your code here

In [ ]:
#import your library
#complete your code here

In [ ]:
#Take the respective inputs
n=(#complete your code here)
m=(#complete your code here)
l1=(#complete your code here)
l2=(#complete your code here)

In [ ]:
#Create a dense layer and use L1 reugalizer.
layer = #complete your code here

In [ ]:
# Create the tensor and apply the regularizer on tensor.
tensor = #complete your code here
out = #complete your code here

In [ ]:
#print the output
print(out)