**Question:** Create a Dense layer with ‘n’ neurons, apply kernel initializer of RandomUniform with min ,max values given and also apply a regularizer of ‘l1’and create a tensor with a multiplier of ‘m’ and pass it through the layer and print the output.


**Level :02**

**Sample Input format:**

Number

Number

Number

Number

Number

Number

**Sample Output format :**

Tensor




**Sample Input:**

6<br/>
2<br/>
0.2<br/>
0<br/>
0.5


**Sample Output:**

tf.Tensor(<br/>[[3.1377742 2.3369114 2.4595098 3.0917711 2.450071  3.7301912]<br/>
 [3.1377742 2.3369114 2.4595098 3.0917711 2.450071  3.7301912]<br/>
 [3.1377742 2.3369114 2.4595098 3.0917711 2.450071  3.7301912]<br/>
 [3.1377742 2.3369114 2.4595098 3.0917711 2.450071  3.7301912]<br/>
 [3.1377742 2.3369114 2.4595098 3.0917711 2.450071  3.7301912]<br/>
 [3.1377742 2.3369114 2.4595098 3.0917711 2.450071  3.7301912]],shape=(6, 6), dtype=float32)


In [ ]:
#start your code here

In [ ]:
#import your library
#complete your code here

In [ ]:
#take the respective inputs
n=(#complete your code here)
m=(#complete your code here)
l1=(#complete your code here)
min_val=(#complete your code here)
max_val=(#complete your code here)

In [ ]:
#Apply the initializer in to a variable
initializer=#complete your code here

In [ ]:
#apply the dense layer with the initializer and regularizer.
layer = #complete your code here

In [ ]:
#create the tensor and apply the layer on it.
tensor =#complete your code here
out = #complete your code here

In [ ]:
#print the output
print(out)