**Question:** Create a dense layer with ‘n’ neurons and apply a L1_L2 regularization penalty of 'l1',‘l2’ ,pass a tensor of shape(n,n) with a multiplier ‘m’ and print the result.

**Level** : Medium

**Input format:**
* Integer
* Integer
* Float
* Float

**Output format :**
* Tensor






**Sample Input:**

6<br/>
2<br/>
0.2<br/>
0.15

**Sample Output:**

tf.Tensor(<br/>[[12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]],shape=(6, 6), dtype=float32)


**SOLUTION**

In [ ]:
#start your code here

In [4]:
#import your library
import tensorflow as tf

In [ ]:
#Take the respective inputs
n=(int(input()))
m=(int(input()))
l1=(float(input()))
l2=(float(input()))

In [14]:
#Create a dense layer and use L1 reugalizer.
layer = tf.keras.layers.Dense(# Complete Your code here , input_dim=5,kernel_initializer='ones',
                              kernel_regularizer= # Complete Your code here


In [15]:
# Create the tensor and apply the regularizer on tensor.
tensor = # Complete Your code here
out = layer(tensor)

In [1]:
#print the output
