**Question:** Create a dense layer with ‘n’ neurons and apply a L2 regularization penalty of ‘l2’ ,pass a tensor of shape(n,n) with a multiplier ‘2’ and print the result.

**Level** : Easy

**Sample Input format:**
* Integer
* Integer
* Float

**Sample Output format :**
* Tensor




**Sample Input:**

6<br/>
2<br/>
0.2


**Sample Output:**

tf.Tensor(<br/>[[12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/> 
 [12. 12. 12. 12. 12. 12.]<br/>
 [12. 12. 12. 12. 12. 12.]],shape=(6, 6), dtype=float32)



**SOLUTION**

In [ ]:
#start your code here

In [1]:
#import your library
import tensorflow as tf

In [ ]:
#Take the respective inputs
n=(int(input()))
m=(int(input()))
l2=(float(input()))

In [13]:
2#Create a dense layer and use L1 reugalizer.
layer = tf.keras.layers.Dense(# Complete Your code here , input_dim=5,kernel_initializer='ones',
                              kernel_regularizer= # Complete Your code here


In [14]:
# Create the tensor and apply the regularizer on tensor.
tensor = # Complete Your code here
out = layer(tensor)

In [1]:
#print the output
