**Question**: Load, split, and preprocess the sarcasm dataset using tokenizer by including vocabulary size as 1000, post padding, and maximum sentence length as 120



**Level**: Easy


**Input format:** json format


**Output format:** array


**Sample input:** Sarcasm dataset


**Sample output**: 

[[  1   1   1 ...   0   0   0]

 [202   1   8 ...   0   0   0]
 
 [ 18 380 191 ...   0   0   0]
 
 ...
 
 [  1   9  67 ...   0   0   0]
 
 [  1 374   1 ...   0   0   0]
 
 [  1   1   6 ...   0   0   0]]


**Solution**:

In [ ]:
import json
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
#Write your code here