**Question :** Create MxN dimensional array.apply transpose,flip left rright(fliplr),flip up and down(flipud),rotate 90 degrees(np.rot90) on created array .and print all outputs.

**Level :** Hard

**Input format :**

Integer   #M represents no.of rows.
Integer   #N represents no.of columns.

M rows of N columns.

**Output format :**

Arrays.

**Sample input :**

2
2
1 2
3 4

**Sample output  :**

In [5]:
# Write Your Code Here.

In [1]:
import numpy as np
m=int(input())
n=int(input())
array2d = np.array([list(map(int,input().split())) for i in range(m)])
arrayT = np.transpose(array2d)
print(arrayT)

2
2
1 2
3 4
[[1 3]
 [2 4]]


In [2]:
arrayFlr = np.fliplr(array2d)
print(arrayFlr)

[[2 1]
 [4 3]]


In [3]:
arrayFud = np.flipud(array2d)
print(arrayFud)

[[3 4]
 [1 2]]


In [4]:
arrayRot90 = np.rot90(array2d)
print(arrayRot90)

[[2 4]
 [1 3]]
