**Question :**

Create an integer numpy array which contains values from 1 to N(inclusive) store it in a variable **arr**.
   
  1)print the reverse of an array **arr** using slice function.

  2)and print the array from 5th element to Nth element if n>5 else print last element in array.

**Level :** Easy

**Input format :** an integer number.

**Output format :** array

**Sample input 1:**

4

**Sample output 1:** 

[4 3 2 1]

4

**Sample input 2 :**

10

**sample output 2 :**

[10  9  8  7  6  5  4  3  2  1]

[ 6  7  8  9 10]

In [10]:
# Write Your Code Here.

In [3]:
import numpy as np
N=int(input())
arr=np.array([int(x) for x in range(1,N+1)])
print(arr[::-1])
if N>5:
    print(arr[5:])
else:
    print(arr[-1])

20
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [35]:
print(np.arange(1,N+1,dtype='int'))

[ 1  2  3  4  5  6  7  8  9 10]
