**Question:** Create a Dense layer with 5 neurons and apply this on tensor of (5,5) with a multiplier 2.5,apply a kernel regularizer L1 and initializer RandomUniform and print the output.

**Description:** 
* Import the required libraries.
* Create a tensor and a dense layer 
* Create a regularizer variable and initializer variable
* Create a tensor with multiplier 
* Apply the layer on tensor and print the output.


**Sample Output format :**

Tensor

**Sample Output:**

tf.Tensor(

tf.Tensor(

[[-0.2880118  -0.01102182 -0.04507724 -0.13479224  0.20802194]

 [-0.2880118  -0.01102182 -0.04507724 -0.13479224  0.20802194]

 [-0.2880118  -0.01102182 -0.04507724 -0.13479224  0.20802194]

 [-0.2880118  -0.01102182 -0.04507724 -0.13479224  0.20802194]

 [-0.2880118  -0.01102182 -0.04507724 -0.13479224  0.20802194]], shape=(5, 5), dtype=float32)

* Hint 01: use tensorflow library
* Hint 02: create a dense layer using tf.keras.layers.Dense()
* Hint 03: for regularizer tf.keras.regularizers,for initializers tf.keras.initializers

In [ ]:
#start your code here

In [1]:
#import library
import tensorflow as tf

In [2]:
#create a tensor
tensor = tf.ones(shape=(5,5))*2.5

In [3]:
initializer=tf.keras.initializers.RandomUniform()
regularizer=tf.keras.regularizers.L1()

In [4]:
#create a dense layer and pass the tensor through it
layer=tf.keras.layers.Dense(5,input_dim=5,kernel_initializer=initializer,kernel_regularizer=regularizer)
output=layer(tensor)

In [5]:
#print the output
print(output)


tf.Tensor(
[[-0.2880118  -0.01102182 -0.04507724 -0.13479224  0.20802194]
 [-0.2880118  -0.01102182 -0.04507724 -0.13479224  0.20802194]
 [-0.2880118  -0.01102182 -0.04507724 -0.13479224  0.20802194]
 [-0.2880118  -0.01102182 -0.04507724 -0.13479224  0.20802194]
 [-0.2880118  -0.01102182 -0.04507724 -0.13479224  0.20802194]], shape=(5, 5), dtype=float32)
