**Question :** Below is the given list and dtype , apply the relu activation function on the list using tf.keras  ([-10, -5, 0.0, 5, 10], dtype = tf.float32)

**Level :** Medium

**Input format :**  

list

**Output format :** 

array

**Sample Input :** 

(df, alpha=0.5).numpy()

**Sample Output :**

array([-5. , -2.5,  0. ,  5. , 10. ], dtype=float32)

In [1]:

import tensorflow as tf
foo = tf.constant([-10, -5, 0.0, 5, 10], dtype = tf.float32)
tf.keras.activations.relu(foo).numpy()



array([ 0.,  0.,  0.,  5., 10.], dtype=float32)

In [2]:
tf.keras.activations.relu(foo, alpha=0.5).numpy()

array([-5. , -2.5,  0. ,  5. , 10. ], dtype=float32)

In [3]:
tf.keras.activations.relu(foo, max_value=5).numpy()

array([0., 0., 0., 5., 5.], dtype=float32)

In [4]:
tf.keras.activations.relu(foo, threshold=5).numpy()

array([-0., -0.,  0.,  0., 10.], dtype=float32)