**Question**: Convert a list into a tensor using TensorFlow.and apply the relu activation function on the created tensor using tf.keras with different parameters such as alpha, max_value, threshold and print each output to console.

**Constraints :**

* Use dtype=float32

* Apply the relu activation function on the list using tf.keras with alpha = 0.5

* Apply the relu activation function on the list using tf.keras with max_value = 5

* Apply the relu activation function on the list using tf.keras with threshold = 5


**Level :** Medium

**Input format :**  Space-separated values.

**Output format :** 

**Sample Input :** 

-10 -5 0 5 10 15 20 25

**Sample Output :**

In [7]:
# Write Your Code Here.

In [10]:
import tensorflow as tf
lst=list(map(int,input().split()))
foo = tf.constant(lst, dtype = tf.float32)
print(tf.keras.activations.relu(foo, alpha=0.5).numpy())
print(tf.keras.activations.relu(foo, max_value=5).numpy())
print(tf.keras.activations.relu(foo, threshold=5).numpy())

1 6 11 16 -11 -6 -1
[ 1.   6.  11.  16.  -5.5 -3.  -0.5]
[1. 5. 5. 5. 0. 0. 0.]
[ 0.  6. 11. 16. -0. -0. -0.]
