**Question:** Create a dense layer of 5 neurons and input dimension of 4 and pass a tensor of shape (4,6) through it and print the output.

**Description:** 
* Import the required libraries.
* Create a tensor and a dense layer 
* Pass the tensor through the layer and print the output.


**Sample Output format :**

Tensor

**Sample Output:**

tf.Tensor(

[[ 2.2181685   0.98955387  1.0103583  -0.69766754  0.69425327]

[ 2.2181685   0.98955387  1.0103583  -0.69766754  0.69425327]

[ 2.2181685   0.98955387  1.0103583  -0.69766754  0.69425327]

[ 2.2181685   0.98955387  1.0103583  -0.69766754  0.69425327]], shape=(4, 5), dtype=float32)

* Hint 01: use tensorflow library
* Hint 02: create a tensor (4,6) with tf.tensor
* Hint 03: create a  dense layer using tf.keras.layers


In [ ]:
#start your code here

In [1]:
#import library
import tensorflow as tf

In [2]:
#create a tensor
tensor = tf.ones(shape=(4,6))

In [3]:
#create a dense layer and pass the tensor through it
layer=tf.keras.layers.Dense(5,input_dim=4)
output=layer(tensor)

In [4]:
#print the output
print(output)


tf.Tensor(
[[ 2.2181685   0.98955387  1.0103583  -0.69766754  0.69425327]
 [ 2.2181685   0.98955387  1.0103583  -0.69766754  0.69425327]
 [ 2.2181685   0.98955387  1.0103583  -0.69766754  0.69425327]
 [ 2.2181685   0.98955387  1.0103583  -0.69766754  0.69425327]], shape=(4, 5), dtype=float32)
