**Question** : Combine range of elements  into 4 batches. Here the given range is 16 using with tf.data


**Level** : Easy

**Input format** : tf.data.Dataset.range


**Output format** : Given range of value converted into given number of batches 

**Sample input** : Use 4 batches for a given range 

**Sample Output** : Array


**SOLUTION**

In [1]:
import tensorflow as tf
df = tf.data.Dataset.range(16)
df = df.batch(4)
list(df.as_numpy_iterator())

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15])]