In [18]:
import numpy as np
import nltk
from nltk import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer 

In [19]:
corpus = [
   'This is the first document.',
    'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
]


In [21]:
cv = CountVectorizer(analyzer='word', ngram_range=(2, 2))

In [22]:
data = cv.fit_transform(corpus)

In [24]:
print(data.toarray())

[[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]
