**Question:** Create a dense layer with ‘5’ neurons and apply aL1  regularization penalty of ‘0.3’ ,pass a tensor of shape(6,6) with a multiplier ‘4.5’ and print the result


**Description:** 
* Import the required libraries.
* Ask for the sample input for creating a tensor of ones,multiplier and also ask for input for the value of  L1 penalty.
* Create a Dense layer.
* Create a tensor with multiplier 
* Apply the layer on tensor and print the output.


**Sample Output format :**

Tensor

**Sample Output:**

tf.Tensor(

[[27. 27. 27. 27. 27.]

 [27. 27. 27. 27. 27.]

 [27. 27. 27. 27. 27.]

 [27. 27. 27. 27. 27.]

 [27. 27. 27. 27. 27.]

 [27. 27. 27. 27. 27.]], shape=(6, 5), dtype=float32)

​

* Hint 01: use tensorflow library
* Hint 02: create dense layer using tf.keras.layers.Dense()
* Hint 03: use regularizers using tf.keras.regularizers.L1


In [ ]:
#start your code here

In [1]:
#import library
import tensorflow as tf

In [2]:
#create a tensor
tensor = tf.ones(shape=(6, 6)) * 4.5

In [3]:
#create a dense layer and pass the tensor through it
layer = tf.keras.layers.Dense(5, input_dim=5,kernel_initializer='ones',kernel_regularizer=tf.keras.regularizers.L1(0.3))
out = layer(tensor)


In [4]:
#print the output
print(out)

tf.Tensor(
[[27. 27. 27. 27. 27.]
 [27. 27. 27. 27. 27.]
 [27. 27. 27. 27. 27.]
 [27. 27. 27. 27. 27.]
 [27. 27. 27. 27. 27.]
 [27. 27. 27. 27. 27.]], shape=(6, 5), dtype=float32)
