**Question :** Apply a dropout layer of 0.3 on an array of range 12 and reshape it to (6,2) and print before and after arrays.


**Explanation:**
* Create a Dropout layer  of 0.3
* Create an array  and reshape it.
* Apply the Dropout layer and print the input and output arrays.


**Sample Output:**

Numpy array

Tensor

**Sample Output:**

[[ 0.  1.  2.  3.]

[ 4.  5.  6.  7.]

[ 8.  9. 10. 11.]

[12. 13. 14. 15.]]

tf.Tensor(

[[ 0.         1.4285715  2.857143   4.285714 ]

[ 5.714286   7.1428576  8.571428  10.       ]

[11.428572  12.857143  14.285715  15.714286 ]

[17.142857   0.         0.        21.428572 ]], shape=(4, 4), dtype=float32)
​

* Hint 01: use tensorflow library,numpy library
* Hint 02: create a dropout layer using tf.keras.layers.Dropout()
* Hint 03: create a array using numpy.arange()


In [1]:
#start your code here

In [1]:
#import libraries
import tensorflow as tf
import numpy

In [2]:
#Create a dropout layer
layer = tf.keras.layers.Dropout(0.3, input_shape=(2,))

In [3]:
#create a numpy array and reshape it and change the datatype
data = numpy.arange(16).reshape(4, 4).astype(numpy.float32)

In [4]:
#Apply the dropout layer on the array
outputs = layer(data, training=True)

In [5]:
#print the input and output
print(data)
print(outputs)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
tf.Tensor(
[[ 0.         1.4285715  2.857143   4.285714 ]
 [ 5.714286   7.1428576  8.571428  10.       ]
 [11.428572  12.857143  14.285715  15.714286 ]
 [17.142857   0.         0.        21.428572 ]], shape=(4, 4), dtype=float32)
