**Question:** Create a Dense layer with 5 neurons and apply this on tensor of (4,4) with a multiplier 3.5,apply a kernel regularizer L1 and initializer GlorotUniform and print the output.

**Description:** 
* Import the required libraries.
* Create a tensor and a dense layer 
* Create a regularizer variable and initializer variable
* Create a tensor with multiplier 
* Apply the layer on tensor and print the output.


**Sample Output format :**

Tensor

**Sample Output:**

tf.Tensor(

[[-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]

 [-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]

 [-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]

 [-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]

 [-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]

 [-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]], shape=(6, 5), dtype=float32)

* Hint 01: use tensorflow library
* Hint 02: create a dense layer using tf.keras.layers.Dense()
* Hint 03: for regularizer tf.keras.regularizers,for initializers tf.keras.initializers

In [ ]:
#start your code here

In [11]:
#import library
import tensorflow as tf

In [12]:
#create a tensor
tensor = tf.ones(shape=(6,6))*1.5

In [13]:
initializer=tf.keras.initializers.RandomNormal()
regularizer=tf.keras.regularizers.L1()

In [14]:
#create a dense layer and pass the tensor through it
layer=tf.keras.layers.Dense(5,input_dim=5,kernel_initializer=initializer,kernel_regularizer=regularizer)
output=layer(tensor)

In [15]:
#print the output
print(output)


tf.Tensor(
[[-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]
 [-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]
 [-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]
 [-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]
 [-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]
 [-0.13295063 -0.15189724 -0.2483059  -0.09455386  0.07673407]], shape=(6, 5), dtype=float32)
