**Question :** Create a tensor of one's shape(5,5) using a tensorflow library and print the tensor. 

**Explanation:**
* TensorFlow is a free and open-source software library for dataflow and differentiable programming across a range of tasks.


**Sample Output:**

Tensor

**Sample Output:**

tf.Tensor(

[[1. 1. 1. 1. 1.]

[1. 1. 1. 1. 1.]

[1. 1. 1. 1. 1.]

[1. 1. 1. 1. 1.]

[1. 1. 1. 1. 1.]], 

shape=(5, 5), dtype=float32)

* Hint 01: use tensorflow library
* Hint 02: create tensor of one’s using tf.ones()


In [1]:
#start your code here

In [1]:
#import library
import tensorflow as tf

In [2]:
#create a tensor
tensor = tf.ones(shape=(5,5)) 

In [3]:
#print the tensor
print(tensor)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)
