**Question :**

Create an integer numpy array which contains values from 1 to N(inclusive) store it in a variable **arr**.
   
  1)print the reverse of an array **arr** using slice function.

  2)and print the array from 5th element to Nth element if n>5 else print last element in array.

**Level :** Easy

**Input format :** an integer number.

**Output format :** array

**Sample input 1:**

4

**Sample output 1:** 

[4 3 2 1]

4

**Sample input 2 :**

10

**sample output 2 :**

[10  9  8  7  6  5  4  3  2  1]

[ 6  7  8  9 10]

In [2]:
import numpy as np
# Write Your Code Here.