**Question**: For a given list apply relu activation function with alpha, max_value and threshold values.

**Description**: 

* Read Space-separated values from input() function  
* Convert Space-separated values into list of float values.
* convert list into tensor using tf.constant() and use dtype=tf.float32.
* Apply the relu activation function on the list using tf.keras
* Apply the relu activation function on the list using tf.keras with alpha = 0.5
* Apply the relu activation function on the list using tf.keras with max_value = 5
* Apply the relu activation function on the list using tf.keras with threshold = 5

**Level**: Medium

**Input format**: Space-separated values.


**Output format**: Arrays

**Sample Input**: 

-20 -15 -10 -5 0 5 10 15 20

**Sample Output**:

[ 0.  0.  0.  0.  0.  5. 10. 15. 20.]

[-10.   -7.5  -5.   -2.5   0.    5.   10.   15.   20. ]

[0. 0. 0. 0. 0. 5. 5. 5. 5.]

[-0. -0. -0. -0.  0.  0. 10. 15. 20.]

In [ ]:
#Start Your Code From Here.

In [1]:
#Import Libraries.
import tensorflow as tf


In [2]:
# Read input and Convert into list.

lst=list(map(int,input().split()))

-20 -15 -10 -5 0 5 10 15 20


In [3]:
# Apply tf.constant() on list and use dtype float32

lst=tf.constant(lst,dtype=tf.float32)

In [4]:
# Apply the relu activation function on tensor

print(tf.keras.activations.relu(lst).numpy())

[ 0.  0.  0.  0.  0.  5. 10. 15. 20.]


In [5]:
# Apply the relu activation function with alpha=0.5

print(tf.keras.activations.relu(lst,alpha=0.5).numpy())

[-10.   -7.5  -5.   -2.5   0.    5.   10.   15.   20. ]


In [6]:
# Apply the relu activation function with max_value=5

print(tf.keras.activations.relu(lst,max_value=5).numpy())

[0. 0. 0. 0. 0. 5. 5. 5. 5.]


In [7]:
# Apply the relu activation function with threshold=5

print(tf.keras.activations.relu(lst,threshold=5).numpy())

[-0. -0. -0. -0.  0.  0. 10. 15. 20.]
