**Question :** Create two (M x N) dimensional arrays X and Y and  Combine X and Y using hstack. Print X,Y and hstack of (X,Y).

**Explanation:**

    M-----→ number of rows.                                         
    
    N-----→ number of columns.                                      
    
    X-----→ NxM dimensional array.                                
    
    Y-----→ NxM dimensional array.
    
   hstack : Stack arrays in sequence horizontally (column wise).
   
   import numpy as np
   
   np.hstack([X,Y])

**Level :** Hard

**Input format :**

The first line contains M,N space-separated values.

in second and third lines, space-seperated values are rows of X.

In the fourth and fifth lines, space-separated values are rows of Y.

**Output format :** Arrays 

**Sample input :**

**Sample output :**

In [ ]:
# Start Your Code Here.

In [3]:
import numpy as np
m,n=list(map(int,input().split()))
x=np.array([list(map(int,input().split())) for _ in range(m)])
y=np.array([list(map(int,input().split())) for _ in range(m)])
print(x)
print(y)
print(np.hstack([x,y]))

2 5
1 2 3 4 5
6 7 8 9 10
11 22 33 44 55
66 77 88 99 11
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 22 33 44 55]
 [66 77 88 99 11]]
[[ 1  2  3  4  5 11 22 33 44 55]
 [ 6  7  8  9 10 66 77 88 99 11]]
