**Question:** Create a Dropout layer,and also create an array and reshape it , take an input to and apply the layer on this reshaped array and print the input and output.

**Level** : Medium

**Input format:**
* Float
* Integer

**Output format:**

* Numpy array
* Tensor




**Sample Input:**

0.5<br/>
20


**Sample Output:**

[[ 0.  1.] <br/> 
 [ 2.  3.] <br/>
 [ 4.  5.] <br/>
 [ 6.  7.] <br/>
 [ 8.  9.] <br/>
 [10. 11.] <br/>
 [12. 13.] <br/>
 [14. 15.] <br/>
 [16. 17.] <br/>
 [18. 19.]] <br/>
tf.Tensor(  <br/>
[[ 0.  0.] <br/>
 [ 4.  6.] <br/>
 [ 0. 10.] <br/>
 [ 0. 14.] <br/>
 [16.  0.] <br/>
 [20. 22.] <br/>
 [24.  0.] <br/>
 [ 0. 30.] <br/>
 [32. 34.] <br/>
 [36.  0.]], shape=(10, 2), dtype=float32)

**SOLUTION**

In [ ]:
#start your code here

In [32]:
#import your library
import tensorflow as tf
import numpy


In [65]:
#take the respective inputs
d=float(input())
n=float(input())


0.5
20


In [66]:
tf.random.set_seed(0)

In [67]:
#Create a dropout layer
layer = tf.keras.layers.Dropout(d, input_shape=(2,))

In [68]:
#create an input array using numpy and reshape
data = numpy.arange(n).reshape(int(n/2), 2).astype(numpy.float32)

In [69]:
#Apply the layer
outputs = layer(data, training=True)

In [70]:
# print the input and output.
print(data)
print(outputs)

[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]
 [12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]]
tf.Tensor(
[[ 0.  0.]
 [ 4.  6.]
 [ 0. 10.]
 [ 0. 14.]
 [16.  0.]
 [20. 22.]
 [24.  0.]
 [ 0. 30.]
 [32. 34.]
 [36.  0.]], shape=(10, 2), dtype=float32)
