**Question:**  

The given text is a sentence to find vector format each document wise using Keras and take above 5 most important words 


**Level:**Easy

**Input format:** given a sentence find countvector using keras

**Output format:** list

**Sample Input:**

Word count After tokenizing a text, the first figure we can calculate is the word frequency.,
By word frequency, we indicate the number of times each token occurs in a text.


**Sample Output:**  

[[0. 1. 0. 1. 1.] <br/>
 [0. 1. 1. 0. 0.] <br/>
 [0. 1. 0. 0. 0.] <br/>
 [0. 0. 1. 1. 1.]] <br/>


**Solution**

In [7]:
import tensorflow as tf

In [13]:
documents=input().split(",")

Natural language processing helps computers communicate with humans in their own language and scales other language-related tasks


In [14]:
t = tf.keras.preprocessing.text.Tokenizer(num_words=5)

In [15]:
t1=t.fit_on_texts(documents)

In [16]:
(documents)

['Natural language processing helps computers communicate with humans in their own language and scales other language-related tasks']

In [17]:
print(t.texts_to_matrix(documents))

[[0. 1. 1. 1. 1.]]
