**Question :**

Create a numpy array with 10 ones and data type as int

Create a numpy array with 5 rows and 5 columns filled with zeros and data type as float

Create a numpy array with following values[9, 3, 6, 5, 8, 4] and store it in abc

**Level :** Medium

**Input format :**

input with data type as integer

input with data type as float

input as integers

**Output format :**

Numpy array with ones

numpy array matrix

array of given values

**Sample input :**

ones(5, dtype='int')

zeros((3,5), dtype=float)

array([4, 3, 4, 4, 8, 4])

**Sample output :**

([1,1,1,1,1])

array([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]])

array([4, 3, 4, 4, 8, 4])

In [ ]:
import numpy as np

# write your code here

